name: Deploy static content to Pages
on:
  push: { branches: ["main"] }
  workflow_dispatch:
permissions: { contents: read, pages: write, id-token: write }
concurrency: { group: "pages", cancel-in-progress: false }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dart Sass
        run: sudo npm i -g sass
      - name: Build site
        run: |
          rm -rf dist
          mkdir -p dist/css dist/js dist/assets
          sass src/css/main.scss dist/css/main.css --no-source-map
          cp src/index.html dist/index.html
          cp -R src/js/* dist/js/ 2>/dev/null || true
          cp -R src/assets/* dist/assets/ 2>/dev/null || true
      - uses: actions/upload-pages-artifact@v3
        with: { path: ./dist }
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: { name: github-pages, url: ${{ steps.deployment.outputs.page_url }} }
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

